### ISSUE TITLE
artifact.cna

### ISSUE THREAD

**Issue by sec13b** [ProcessusT/Venoma#2]
what cs version you run , and can you upload your "artifact.cna"

![image](https://github.com/ProcessusT/Venoma/assets/123419537/1b9730fb-5414-42b7-a8de-af6057819d0a)

**Comment by ProcessusT** [comment]
I use a Cobalt Strike version over 4.7, but I can't upload the aggressor script because maybe it violates the terms of use, you need to take yours.

**Comment by sec13b** [comment]
ok thank you

**Comment by sec13b** [comment]
can u send  your artifact cna to sec13b  yopmail com

thank you
